# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Java Maven Build and Publish Artifacts

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  publish-job:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - run: mkdir dev && cp target/*.jar dev
    - uses: actions/upload-artifact@v3
      with:
        name: Package
        path: dev
        
    - name: Deploy the package to the remote server
      uses: garygrossgarten/github-action-scp@release
      with:
        local: /dev/nahid1-0.0.2-SNAPSHOT.jar
        remote: home/ec2-user/ # My remote directory
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Run a script on remote server (start the application)
      if: always()
      uses: fifsky/ssh-action@master
      with:
        command: |
          cd home/ec2-user/ && java -jar nahid1-0.0.2-SNAPSHOT.jar &
        host: ${{ secrets.HOST }}
        username: ${{ secrets.SSH_USER }}
        privateKey: ${{ secrets.SSH_PRIVATE_KEY }}
        args: "-tt"
        # The & in the command runs the process on background
    
